### ISSUE TITLE
Doesn't run on windows 

### ISSUE THREAD

**Issue by Animexxl** [ChromiumOS-Guy/SuperPatcherGSI#1]
outputs this error lpunpack.py: error: unrecognized arguments: m11\windows/tmp
the /tmp i assume is a linux thing since windows uses \

**Comment by ChromiumOS-Guy** [comment]
it worked on my windows 11 VM,
but ill check it on win10 today maybe it accepts it on my install because I have different python version ?

**Comment by Animexxl** [comment]
I use the same python version.....maybe it's how the script handles temp files.. because it brought an error before about not finding the \tmp folder then after manually creating the tmp folder it brought the error above

**Comment by ChromiumOS-Guy** [comment]
wait.. do you have writing prems on windows (maybe thats your problem),
also I checked and Shutils uses same syntax in linux & windows so the code should work

**Comment by ChromiumOS-Guy** [comment]
I mean it worked for me on win11 with the provided python version with the same code so your setup is probably different somehow and that messes with the code ?,the code worked on a win10 PC I didn't manage to recreate the error
(you can try to hard code a path)
from:
`TempDIR = os.getcwd() + "/" + "tmp"`
to:
`TempDIR = "some dir on pc" + "/tmp"`
or (maybe will work):
`TempDIR = "some dir on pc" + "\tmp"`

**Comment by ChromiumOS-Guy** [comment]
if that doesn't work you can try updating lpunpack from here:
https://github.com/unix3dgforce/lpunpack

**Comment by ChromiumOS-Guy** [comment]
wait got replication I'm testing it

**Comment by ChromiumOS-Guy** [comment]
its totally a change in syntax thanks windows !!

**Comment by ChromiumOS-Guy** [comment]
also found another bug so nice on that

**Comment by ChromiumOS-Guy** [comment]
I'm downloading a different rom maybe its corrupted super.img

**Comment by ChromiumOS-Guy** [comment]
are you by chance running the script from a driver which is not the C: drive because moving it to C: appears to fix the problem ? (I'll make known bugs list and add this bug to it)

**Comment by ChromiumOS-Guy** [comment]
let me elaborate it seems that when input with any path which doesn't start with C: drive it breaks there is no apparent cause it just happens.
