### ISSUE TITLE
Can't run in Ubuntu x86-64 with Rosetta (Mac OS with Parallels Desktop)

### ISSUE THREAD

**Issue by mzwir** [ChromiumOS-Guy/SuperPatcherGSI#10]
I can't run this script using Ubuntu with Rosetta 
<img width="804" alt="Screenshot 2024-10-18 at 19 45 26" src="https://github.com/user-attachments/assets/08234cb3-d478-40da-b262-2ca5f3dd22fc">

How to solve this?

**Comment by ChromiumOS-Guy** [comment]
This seems like a privileges error, try extracting the appimage and running AppRun directly after chmod +x * to all the contents.
See if this works.
