### ISSUE TITLE
Was trying to use SuperPatcherGSI till I got this error

### ISSUE THREAD

**Issue by pparaxan** [ChromiumOS-Guy/SuperPatcherGSI#5]
`usage: SuperPatcherGSI.py [-i INPUT] [-o OUTPUT] [-s SLOT]
SuperPatcherGSI.py: error: argument -s/--SLOT: invalid int value: ''`

can anyone help

**Comment by pparaxan** [comment]
./SuperPatcherGSI-x64.AppImage -i super.img -o patched.img -g dotOS-R-v5.2-arm32-binder64-ab-VANILLA-OFFICIAL.img -s 1

**Comment by pparaxan** [comment]
fixed: moved -s 1 from the end to the start

**Comment by ChromiumOS-Guy** [comment]
There is no GSI flag anymore it has been moved into user input at runtime so everything you put after that flag isn't registered because it doesn't exist
Edit:
Referring to the -g flag (GSI)

**Comment by pparaxan** [comment]
Ohk
