### ISSUE TITLE
Add Free Spaces

### ISSUE THREAD

**Issue by teerasak** [ChromiumOS-Guy/SuperPatcherGSI#6]
Please add specific free spaces for super. thank you.

**Comment by ChromiumOS-Guy** [comment]
Will do after i finish working on my other project (the 6502PC)

**Comment by ChromiumOS-Guy** [comment]
okay I'm back I'm going to add the ability to specify a "ghost" partition with size of x as long as x % 512 returns 0

**Comment by ChromiumOS-Guy** [comment]
actually just noticed i already check for that in code lol so scratch  x % 512 returns 0 it can be whatever

**Comment by ChromiumOS-Guy** [comment]
Added it you're welcome.
